"""Verify that every checked-in test vector is regenerated byte-for-byte
by the current Python implementation, and that decoding the .out.bin
yields back the inputs from the .in.json.

This is the interop contract: every language impl of Bedrock Echo must
pass this same test (against the same files).
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from echo import proto, crypto  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[2]
VECTOR_DIR = REPO_ROOT / "testvectors"


def _pairs():
    for json_path in sorted(VECTOR_DIR.glob("*.in.json")):
        bin_path = json_path.with_suffix("").with_suffix(".out.bin")
        yield json_path.stem.removesuffix(".in"), json_path, bin_path


@pytest.mark.parametrize("name,json_path,bin_path", list(_pairs()),
                         ids=lambda p: p if isinstance(p, str) else str(p))
def test_vector_encode_matches(name: str, json_path: Path, bin_path: Path):
    inp = json.loads(json_path.read_text())
    expected = bin_path.read_bytes()

    mt = inp["msg_type"]
    ck = bytes.fromhex(inp["cluster_key"]) if "cluster_key" in inp else None

    if mt.startswith("0x01"):
        hb = proto.Heartbeat(
            sender_id=bytes.fromhex(inp["sender_id"]),
            sequence=inp["sequence"],
            timestamp_ms=inp["timestamp_ms"],
            query_target_id=bytes.fromhex(inp["query_target_id"]),
            own_payload=bytes.fromhex(inp["own_payload"]),
        )
        actual = hb.encode(ck)
    elif mt.startswith("0x02"):
        entries = tuple(
            proto.ListEntry(
                peer_sender_id=bytes.fromhex(e["peer_sender_id"]),
                peer_ipv4=proto.ipv4_to_bytes(e["peer_ipv4"]),
                last_seen_seconds=e["last_seen_seconds"],
            ) for e in inp["entries"]
        )
        sl = proto.StatusList(
            sender_id=bytes.fromhex(inp["witness_sender_id"]),
            sequence=inp["sequence"],
            timestamp_ms=inp["timestamp_ms"],
            witness_uptime_ms=inp["witness_uptime_ms"],
            entries=entries,
        )
        actual = sl.encode(ck)
    elif mt.startswith("0x03"):
        kwargs = dict(
            sender_id=bytes.fromhex(inp["witness_sender_id"]),
            sequence=inp["sequence"],
            timestamp_ms=inp["timestamp_ms"],
            witness_uptime_ms=inp["witness_uptime_ms"],
            target_sender_id=bytes.fromhex(inp["target_sender_id"]),
            status=inp["status"],
        )
        if inp["status"] == 0:
            kwargs.update(
                peer_ipv4=proto.ipv4_to_bytes(inp["peer_ipv4"]),
                last_seen_seconds=inp["last_seen_seconds"],
                peer_payload=bytes.fromhex(inp["peer_payload"]),
            )
        actual = proto.StatusDetail(**kwargs).encode(ck)
    elif mt.startswith("0x10"):
        us = proto.UnknownSource(
            sender_id=bytes.fromhex(inp["witness_sender_id"]),
            sequence=inp["sequence"],
            timestamp_ms=inp["timestamp_ms"],
        )
        actual = us.encode()
    elif mt.startswith("0x20"):
        bs = proto.Bootstrap(
            sender_id=bytes.fromhex(inp["sender_id"]),
            sequence=inp["sequence"],
            timestamp_ms=inp["timestamp_ms"],
            cluster_key=bytes.fromhex(inp["cluster_key"]),
            init_payload=bytes.fromhex(inp["init_payload"]),
        )
        actual = bs.encode(
            witness_x25519_pub=bytes.fromhex(inp["witness_x25519_pub"]),
            eph_priv=bytes.fromhex(inp["eph_priv"]),
        )
    elif mt.startswith("0x21"):
        ack = proto.BootstrapAck(
            sender_id=bytes.fromhex(inp["witness_sender_id"]),
            sequence=inp["sequence"],
            timestamp_ms=inp["timestamp_ms"],
            status=inp["status"],
            witness_uptime_ms=inp["witness_uptime_ms"],
        )
        actual = ack.encode(ck)
    else:
        pytest.skip(f"unknown msg_type {mt}")
        return

    assert actual == expected, (
        f"vector {name}: encode mismatch\n"
        f"  expected ({len(expected)} B): {expected.hex()}\n"
        f"  actual   ({len(actual)} B): {actual.hex()}"
    )


@pytest.mark.parametrize("name,json_path,bin_path", list(_pairs()),
                         ids=lambda p: p if isinstance(p, str) else str(p))
def test_vector_decode_roundtrip(name: str, json_path: Path, bin_path: Path):
    inp = json.loads(json_path.read_text())
    wire = bin_path.read_bytes()
    mt = inp["msg_type"]
    ck = bytes.fromhex(inp["cluster_key"]) if "cluster_key" in inp else None

    if mt.startswith("0x01"):
        out = proto.decode_heartbeat(wire, ck)
        assert out.sender_id == bytes.fromhex(inp["sender_id"])
        assert out.query_target_id == bytes.fromhex(inp["query_target_id"])
        assert out.own_payload == bytes.fromhex(inp["own_payload"])
        assert out.sequence == inp["sequence"]
    elif mt.startswith("0x02"):
        out = proto.decode_status_list(wire, ck)
        assert len(out.entries) == len(inp["entries"])
        for e_actual, e_inp in zip(out.entries, inp["entries"]):
            assert e_actual.peer_sender_id == bytes.fromhex(e_inp["peer_sender_id"])
            assert proto.ipv4_from_bytes(e_actual.peer_ipv4) == e_inp["peer_ipv4"]
            assert e_actual.last_seen_seconds == e_inp["last_seen_seconds"]
    elif mt.startswith("0x03"):
        out = proto.decode_status_detail(wire, ck)
        assert out.target_sender_id == bytes.fromhex(inp["target_sender_id"])
        assert out.status == inp["status"]
        if inp["status"] == 0:
            assert proto.ipv4_from_bytes(out.peer_ipv4) == inp["peer_ipv4"]
            assert out.peer_payload == bytes.fromhex(inp["peer_payload"])
    elif mt.startswith("0x10"):
        out = proto.decode_unknown_source(wire)
        assert out.sender_id == bytes.fromhex(inp["witness_sender_id"])
        assert out.sequence == inp["sequence"]
    elif mt.startswith("0x20"):
        out = proto.decode_bootstrap(wire, bytes.fromhex(inp["witness_x25519_priv"]))
        assert out.sender_id == bytes.fromhex(inp["sender_id"])
        assert out.cluster_key == bytes.fromhex(inp["cluster_key"])
        assert out.init_payload == bytes.fromhex(inp["init_payload"])
    elif mt.startswith("0x21"):
        out = proto.decode_bootstrap_ack(wire, ck)
        assert out.status == inp["status"]
        assert out.witness_uptime_ms == inp["witness_uptime_ms"]
    else:
        pytest.skip(f"unknown msg_type {mt}")
